allowBuilds:
  "@google/genai": true
  "@sentry/cli": true
  agent-browser: true
  better-sqlite3: true
  core-js: true
  cpu-features: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  koffi: true
  msgpackr-extract: true
  node-pty: true
  node-llama-cpp: true
  parallel-web-cli: true
  protobufjs: true
  sqlite-vec: true
  ssh2: true
  tree-sitter-go: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
