mbtn_right  script-binding uosc/menu
tab         script-binding uosc/toggle-ui

space        cycle pause; script-binding uosc/flash-pause-indicator
left         seek -5; script-binding uosc/flash-timeline
right        seek 5; script-binding uosc/flash-timeline
shift+left   seek -30; script-binding uosc/flash-timeline
shift+right  seek 30; script-binding uosc/flash-timeline
up           no-osd add volume 5; script-binding uosc/flash-volume
down         no-osd add volume -5; script-binding uosc/flash-volume
m            no-osd cycle mute; script-binding uosc/flash-volume

s      script-binding uosc/subtitles                    #! Subtitles
a      script-binding uosc/audio                        #! Audio tracks
v      script-binding uosc/video                        #! Video tracks
p      script-binding uosc/items                        #! Playlist
c      script-binding uosc/chapters                     #! Chapters
o      script-binding uosc/open-file                    #! Open file
F      script-binding quality_menu/video_formats_toggle #! Stream quality > Video
alt+f  script-binding quality_menu/audio_formats_toggle #! Stream quality > Audio
#      script-binding uosc/keybinds                     #! Utilities > Key bindings
#      async screenshot                                 #! Utilities > Screenshot
#      cycle ontop                                      #! Utilities > Stay on top
#      cycle fullscreen                                 #! Utilities > Fullscreen
q      quit                                             #! Quit
