variables: media-feed-variables.yml

tasks:
  not-nyaa:
    rss:
      url: https://nyaa.si/?page=rss&q=one+piece&c=3_0&f=1&u=quentintarantado
      link:
        - link
        - magneturi
    series:
      - One Piece:
          identified_by: sequence
          sequence_regexp: '(?i)(?:chapter[ ._-]*)?([0-9]{4}(?:\.[0-9]+)?)'
          begin: '{? one_piece_begin ?}'
    transmission:
      host: 127.0.0.1
      port: 9091
      path: '/Users/bdsqqq/kindle/one piece'
